## Numpy

Импортировать NumPy под именем np

In [4]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [26]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Создать вектор размера 10, заполненный единицами

In [25]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Создать вектор размера 10, заполненный числом 2.5

In [24]:
np.array([2.5] * 10)

array([ 2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [23]:
z = np.zeros(10)
z[4] = 1
z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

Развернуть вектор (первый становится последним)

In [12]:
x = np.array([1, 2, 3, 4, 5])
x[::-1]

array([5, 4, 3, 2, 1])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [22]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [70]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

Создать 3x3 единичную матрицу

In [21]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Создать массив 3x3x3 со случайными значениями

In [29]:
np.random.rand(3, 3, 3)

array([[[ 0.33070332,  0.61958056,  0.17244819],
        [ 0.3411079 ,  0.4266128 ,  0.07118942],
        [ 0.4821929 ,  0.6651722 ,  0.87420111]],

       [[ 0.84958015,  0.415622  ,  0.76937087],
        [ 0.98721471,  0.91816402,  0.34353655],
        [ 0.51804746,  0.71269752,  0.74929745]],

       [[ 0.83549201,  0.37361225,  0.1352717 ],
        [ 0.25431775,  0.52905458,  0.13969939],
        [ 0.87024192,  0.39096507,  0.08842392]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [32]:
x = np.random.rand(30)
np.average(x)

0.60564529859321026

Перемножить матрицы 5x3 и 3x2

In [147]:
a = np.arange(15).reshape((5, 3))
b = np.arange(6).reshape((3, 2))
print(a)
print(b)
a.dot(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [44]:
np.random.uniform(0, 1, 10)

array([ 0.30880513,  0.1267198 ,  0.99762545,  0.46507179,  0.22554715,
        0.62541927,  0.45439031,  0.64092231,  0.46907234,  0.52271578])

Заменить максимальный элемент на ноль

In [55]:
x = np.array([1, 2, 6, 4, 5])
x[x.argmax()] = 0
x

array([1, 2, 0, 4, 5])

Преобразовать массив из float в int

In [56]:
x = np.array([1.5, 2.6, 3.7])
x.astype(int)

array([1, 2, 3])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [142]:
# Здесь я не совсем уверен что правильно понял, то что надо сделать
coords = np.random.random((10, 2))
print(coords)
axes = coords[:,0], coords[:,1]
for asix1 in axes:
    for v1 in asix1:
        s = np.array([v1] * 10)
        for asix2 in axes:
            print(np.diff([s, asix2], axis=0))

[[ 0.73284566  0.03451513]
 [ 0.43815199  0.12896199]
 [ 0.59916677  0.11759519]
 [ 0.35073914  0.23640517]
 [ 0.7157424   0.35638015]
 [ 0.36534272  0.62824142]
 [ 0.40846213  0.11844359]
 [ 0.82819937  0.5223803 ]
 [ 0.11563321  0.6246321 ]
 [ 0.42203283  0.88197267]]
[[ 0.         -0.29469367 -0.13367889 -0.38210652 -0.01710326 -0.36750294
  -0.32438354  0.09535371 -0.61721245 -0.31081284]]
[[-0.69833053 -0.60388367 -0.61525047 -0.49644049 -0.37646551 -0.10460424
  -0.61440207 -0.21046536 -0.10821356  0.14912701]]
[[ 0.29469367  0.          0.16101478 -0.08741285  0.27759041 -0.07280927
  -0.02968987  0.39004738 -0.32251878 -0.01611917]]
[[-0.40363686 -0.30919    -0.3205568  -0.20174682 -0.08177184  0.19008943
  -0.3197084   0.08422831  0.18648011  0.44382068]]
[[ 0.13367889 -0.16101478  0.         -0.24842763  0.11657563 -0.23382405
  -0.19070465  0.2290326  -0.48353356 -0.17713395]]
[[-0.56465164 -0.47020478 -0.48157158 -0.3627616  -0.24278662  0.02907464
  -0.48072318 -0.07678647

Случайно расположить p элементов в 2D массив

In [126]:
a = np.arange(8)
np.random.shuffle(a)
a = a.reshape((2, 4))
a

array([[2, 0, 5, 6],
       [7, 3, 4, 1]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [144]:
a = np.array([1, 2, 3, 4, 5])
b = np.zeros(len(a) + (len(a) - 1) * 3)
b[::3+1] = a
b

array([ 1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  4.,
        0.,  0.,  0.,  5.])

Найти наиболее частое значение в массиве

In [146]:
a = np.array([1, 2, 3, 1, 2, 1, 1, 1, 3, 2, 2, 1])
counts = np.bincount(a)
np.argmax(counts)

1

Найти n наибольших значений в массиве

In [159]:
n = 5
a = np.array([10, 21, 13, 1, 2, 5, 7, 81, 31, 12, 21])
a = np.sort(a)
print(a)
a[-n:]

[ 1  2  5  7 10 12 13 21 21 31 81]


array([13, 21, 21, 31, 81])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [12]:
import pandas as pd
df = pd.DataFrame.from_csv('en.openfoodfacts.org.products.tsv', sep='\t')

/Users/andrewlarin/anaconda2/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2821: DtypeWarning: Columns (3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):


Посмотреть первые 5 записей

In [13]:
df.head(5)

url  \
code                                                               
0000000003087  http://world-en.openfoodfacts.org/product/0000...   
0000000004530  http://world-en.openfoodfacts.org/product/0000...   
0000000004559  http://world-en.openfoodfacts.org/product/0000...   
0000000016087  http://world-en.openfoodfacts.org/product/0000...   
0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                                  creator   created_t      created_datetime  \
code                                                                          
0000000003087  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
0000000004530             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
0000000004559             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
0000000016087             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
0000000016094             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

              last_modified_t last_modified_datetime  \
code                                                   
0000000003087      1474103893   2016-09-17T09:18:13Z   
0000000004530      1489069957   2017-03-09T14:32:37Z   
0000000004559      1489069957   2017-03-09T14:32:37Z   
0000000016087      1489055731   2017-03-09T10:35:31Z   
0000000016094      1489055653   2017-03-09T10:34:13Z   

                                 product_name generic_name quantity packaging  \
code                                                                            
0000000003087              Farine de blé noir          NaN      1kg       NaN   
0000000004530  Banana Chips Sweetened (Whole)          NaN      NaN       NaN   
0000000004559                         Peanuts          NaN      NaN       NaN   
0000000016087          Organic Salted Nut Mix          NaN      NaN       NaN   
0000000016094                 Organic Polenta          NaN      NaN       NaN   

                      ...         fruits-vegetables-nuts_100g  \
code                  ...                                       
0000000003087         ...                                 NaN   
0000000004530         ...                                 NaN   
0000000004559         ...                                 NaN   
0000000016087         ...                                 NaN   
0000000016094         ...                                 NaN   

              fruits-vegetables-nuts-estimate_100g  \
code                                                 
0000000003087                                  NaN   
0000000004530                                  NaN   
0000000004559                                  NaN   
0000000016087                                  NaN   
0000000016094                                  NaN   

              collagen-meat-protein-ratio_100g cocoa_100g chlorophyl_100g  \
code                                                                        
0000000003087                              NaN        NaN             NaN   
0000000004530                              NaN        NaN             NaN   
0000000004559                              NaN        NaN             NaN   
0000000016087                              NaN        NaN             NaN   
0000000016094                              NaN        NaN             NaN   

              carbon-footprint_100g nutrition-score-fr_100g  \
code                                                          
0000000003087                   NaN                     NaN   
0000000004530                   NaN                    14.0   
0000000004559                   NaN                     0.0   
0000000016087                   NaN                    12.0   
0000000016094                   NaN                     NaN   

              nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
code                                                                           
0000000003087                     NaN                 NaN                 NaN  
000000000453

Сколько наблюдений в наборе данных?


In [34]:
df.shape[0]

356027

Сколько столбцов в наборе данных?

In [21]:
len(df.columns)

162

Напечатайте все названия столбцов

In [22]:
for c in df.columns:
    print(c)

url
creator
created_t
created_datetime
last_modified_t
last_modified_datetime
product_name
generic_name
quantity
packaging
packaging_tags
brands
brands_tags
categories
categories_tags
categories_en
origins
origins_tags
manufacturing_places
manufacturing_places_tags
labels
labels_tags
labels_en
emb_codes
emb_codes_tags
first_packaging_code_geo
cities
cities_tags
purchase_places
stores
countries
countries_tags
countries_en
ingredients_text
allergens
allergens_en
traces
traces_tags
traces_en
serving_size
no_nutriments
additives_n
additives
additives_tags
additives_en
ingredients_from_palm_oil_n
ingredients_from_palm_oil
ingredients_from_palm_oil_tags
ingredients_that_may_be_from_palm_oil_n
ingredients_that_may_be_from_palm_oil
ingredients_that_may_be_from_palm_oil_tags
nutrition_grade_uk
nutrition_grade_fr
pnns_groups_1
pnns_groups_2
states
states_tags
states_en
main_category
main_category_en
image_url
image_small_url
energy_100g
energy-from-fat_100g
fat_100g
saturated-fat_100g
-butyric-a

Какое название у 105 столбца?

In [25]:
df.columns[105]

'-lactose_100g'

Какой тип наблюдений в 105 столбце?

In [28]:
df.dtypes[df.columns[105]]

dtype('float64')

Как проиндексирован набор данных?

In [38]:
for i in df.index.values[:10]:
    print(i)

0000000003087
0000000004530
0000000004559
0000000016087
0000000016094
0000000016100
0000000016117
0000000016124
0000000016193
0000000016513


Каково значение имени продукта в 19-м наблюдении?

In [43]:
df.loc[df.index.values[19]].product_name

'Organic Oat Groats'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [82]:
import io
import requests
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
r = requests.get(url)
chipo = pd.DataFrame.from_csv(io.StringIO(r.content.decode('utf-8')), sep='\t')
chipo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4622 entries, 1 to 1834
Data columns (total 4 columns):
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(1), object(3)
memory usage: 180.5+ KB


Как много продуктов стоят более чем $10.00?

In [81]:
def price_to_int(price):
    return float(price[1:])
chipo2 = chipo.copy().dropna(subset=['item_price'])
chipo2.item_price = chipo2.item_price.apply(price_to_int)
chipo2 = chipo2.loc[chipo2.item_price > 10.0]
len(chipo2)

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [83]:
chipo[['item_name','item_price']]

item_name item_price
order_id                                                  
1                  Chips and Fresh Tomato Salsa     $2.39 
1                                          Izze     $3.39 
1                              Nantucket Nectar     $3.39 
1         Chips and Tomatillo-Green Chili Salsa     $2.39 
2                                  Chicken Bowl    $16.98 
3                                  Chicken Bowl    $10.98 
3                                 Side of Chips     $1.69 
4                                 Steak Burrito    $11.75 
4                              Steak Soft Tacos     $9.25 
5                                 Steak Burrito     $9.25 
5                           Chips and Guacamole     $4.45 
6                          Chicken Crispy Tacos     $8.75 
6                            Chicken Soft Tacos     $8.75 
7                                  Chicken Bowl    $11.25 
7                           Chips and Guacamole     $4.45 
8         Chips and Tomatillo-Green Chili Salsa     $2.39 
8                               Chicken Burrito     $8.49 
9                               Chicken Burrito     $8.49 
9                                   Canned Soda     $2.18 
10                                 Chicken Bowl     $8.75 
10                          Chips and Guacamole     $4.45 
11                             Barbacoa Burrito     $8.99 
11                             Nantucket Nectar     $3.39 
12                              Chicken Burrito    $10.98 
12                                         Izze     $3.39 
13                 Chips and Fresh Tomato Salsa     $2.39 
13                                 Chicken Bowl     $8.49 
14                             Carnitas Burrito     $8.99 
14                                  Canned Soda     $1.09 
15                              Chicken Burrito     $8.49 
...                                         ...        ...
1825                           Barbacoa Burrito    $11.75 
1825                              Carnitas Bowl    $11.75 
1825                              Barbacoa Bowl    $11.75 
1826                               Chicken Bowl     $8.75 
1826                        Chips and Guacamole     $4.45 
1826                          Canned Soft Drink     $1.25 
1826                              Bottled Water     $1.50 
1827                               Chicken Bowl     $8.75 
1827                        Chips and Guacamole     $4.45 
1827                          Canned Soft Drink     $1.25 
1827                           Barbacoa Burrito     $9.25 
1827                           Barbacoa Burrito     $9.25 
1828                               Chicken Bowl     $8.75 
1828                        Chips and Guacamole     $4.45 
1828                          Canned Soft Drink     $1.25 
1829                              Steak Burrito    $11.75 
1829                             Veggie Burrito    $11.25 
1829                          Canned Soft Drink     $1.25 
1830                              Steak Burrito    $11.75 
1830                             Veggie Burrito    $11.25 
1831                              Carnitas Bowl     $9.25 
1831                                      Chips     $2.15 
1831                              Bottled Water     $1.50 
1832                         Chicken Soft Tacos     $8.75 
1832                        Chips and Guacamole     $4.45 
1833                              Steak Burrito    $11.75 
1833                              Steak Burrito    $11.75 
1834                         Chicken Salad Bowl    $11.25 
1834                         Chicken Salad Bowl     $8.75 
1834                         Chicken Salad Bowl     $8.75 

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [94]:
chipo[['item_name','item_price']].sort_values('item_name')

item_name item_price
order_id                              
1360      6 Pack Soft Drink    $12.98 
148       6 Pack Soft Drink     $6.49 
749       6 Pack Soft Drink     $6.49 
754       6 Pack Soft Drink     $6.49 
1076      6 Pack Soft Drink     $6.49 
1373      6 Pack Soft Drink     $6.49 
230       6 Pack Soft Drink     $6.49 
774       6 Pack Soft Drink     $6.49 
776       6 Pack Soft Drink     $6.49 
784       6 Pack Soft Drink     $6.49 
1537      6 Pack Soft Drink     $6.49 
129       6 Pack Soft Drink     $6.49 
798       6 Pack Soft Drink     $6.49 
481       6 Pack Soft Drink     $6.49 
1554      6 Pack Soft Drink     $6.49 
465       6 Pack Soft Drink     $6.49 
1558      6 Pack Soft Drink     $6.49 
849       6 Pack Soft Drink     $6.49 
1196      6 Pack Soft Drink     $6.49 
1803      6 Pack Soft Drink     $6.49 
1664      6 Pack Soft Drink     $6.49 
1666      6 Pack Soft Drink     $6.49 
1800      6 Pack Soft Drink     $6.49 
1798      6 Pack Soft Drink     $6.49 
1525      6 Pack Soft Drink     $6.49 
949       6 Pack Soft Drink     $6.49 
1248      6 Pack Soft Drink     $6.49 
1253      6 Pack Soft Drink     $6.49 
264       6 Pack Soft Drink     $6.49 
422       6 Pack Soft Drink     $6.49 
...                     ...        ...
1192           Veggie Salad     $8.49 
1263           Veggie Salad     $8.49 
1635           Veggie Salad     $8.49 
686            Veggie Salad     $8.49 
1094           Veggie Salad     $8.49 
1677      Veggie Salad Bowl    $11.25 
760       Veggie Salad Bowl    $11.25 
195       Veggie Salad Bowl    $11.25 
1289      Veggie Salad Bowl    $11.25 
896       Veggie Salad Bowl     $8.75 
913       Veggie Salad Bowl     $8.75 
1805      Veggie Salad Bowl     $8.75 
1321      Veggie Salad Bowl     $8.75 
83        Veggie Salad Bowl    $11.25 
394       Veggie Salad Bowl     $8.75 
536       Veggie Salad Bowl     $8.75 
869       Veggie Salad Bowl    $11.25 
1700      Veggie Salad Bowl    $11.25 
128       Veggie Salad Bowl    $11.25 
1818      Veggie Salad Bowl     $8.75 
1066      Veggie Salad Bowl     $8.75 
207       Veggie Salad Bowl    $11.25 
1646      Veggie Salad Bowl    $11.25 
304       Veggie Soft Tacos    $11.25 
1559      Veggie Soft Tacos    $16.98 
948       Veggie Soft Tacos     $8.75 
322       Veggie Soft Tacos     $8.75 
1132      Veggie Soft Tacos     $8.49 
688       Veggie Soft Tacos    $11.25 
567       Veggie Soft Tacos     $8.49 

[4622 rows x 2 columns]

Сколько было заказано самого дорогого предмета?

In [99]:
chipo3 = chipo.copy().dropna(subset=['item_price'])
chipo3.item_price = chipo3.item_price.apply(price_to_int)
max_price = chipo3.item_price.max()
chipo3.loc[chipo3.item_price == max_price].shape[0]

1

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [102]:
chipo.loc[chipo.item_name == 'Veggie Salad Bowl'].shape[0]

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [134]:
chipo4 = chipo.copy().dropna(subset=['choice_description'])
vc = chipo4.loc[chipo4.item_name == 'Canned Soda'] \
    .groupby(['item_name', 'choice_description'])['choice_description'].value_counts()
print(vc)
len(vc[vc > 1])

item_name    choice_description  choice_description
Canned Soda  [Coca Cola]         [Coca Cola]           26
             [Diet Coke]         [Diet Coke]           15
             [Diet Dr. Pepper]   [Diet Dr. Pepper]     13
             [Dr. Pepper]        [Dr. Pepper]          18
             [Mountain Dew]      [Mountain Dew]        15
             [Sprite]            [Sprite]              17
Name: choice_description, dtype: int64


6