## Numpy

Импортировать NumPy под именем np

In [4]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [26]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Создать вектор размера 10, заполненный единицами

In [25]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Создать вектор размера 10, заполненный числом 2.5

In [24]:
np.array([2.5] * 10)

array([ 2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [23]:
z = np.zeros(10)
z[4] = 1
z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

Развернуть вектор (первый становится последним)

In [12]:
x = np.array([1, 2, 3, 4, 5])
x[::-1]

array([5, 4, 3, 2, 1])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [22]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [70]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

Создать 3x3 единичную матрицу

In [21]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Создать массив 3x3x3 со случайными значениями

In [29]:
np.random.rand(3, 3, 3)

array([[[ 0.33070332,  0.61958056,  0.17244819],
        [ 0.3411079 ,  0.4266128 ,  0.07118942],
        [ 0.4821929 ,  0.6651722 ,  0.87420111]],

       [[ 0.84958015,  0.415622  ,  0.76937087],
        [ 0.98721471,  0.91816402,  0.34353655],
        [ 0.51804746,  0.71269752,  0.74929745]],

       [[ 0.83549201,  0.37361225,  0.1352717 ],
        [ 0.25431775,  0.52905458,  0.13969939],
        [ 0.87024192,  0.39096507,  0.08842392]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [32]:
x = np.random.rand(30)
np.average(x)

0.60564529859321026

Перемножить матрицы 5x3 и 3x2

In [147]:
a = np.arange(15).reshape((5, 3))
b = np.arange(6).reshape((3, 2))
print(a)
print(b)
a.dot(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [44]:
np.random.uniform(0, 1, 10)

array([ 0.30880513,  0.1267198 ,  0.99762545,  0.46507179,  0.22554715,
        0.62541927,  0.45439031,  0.64092231,  0.46907234,  0.52271578])

Заменить максимальный элемент на ноль

In [55]:
x = np.array([1, 2, 6, 4, 5])
x[x.argmax()] = 0
x

array([1, 2, 0, 4, 5])

Преобразовать массив из float в int

In [56]:
x = np.array([1.5, 2.6, 3.7])
x.astype(int)

array([1, 2, 3])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [142]:
# Здесь я не совсем уверен что правильно понял, то что надо сделать
coords = np.random.random((10, 2))
print(coords)
axes = coords[:,0], coords[:,1]
for asix1 in axes:
    for v1 in asix1:
        s = np.array([v1] * 10)
        for asix2 in axes:
            print(np.diff([s, asix2], axis=0))

[[ 0.73284566  0.03451513]
 [ 0.43815199  0.12896199]
 [ 0.59916677  0.11759519]
 [ 0.35073914  0.23640517]
 [ 0.7157424   0.35638015]
 [ 0.36534272  0.62824142]
 [ 0.40846213  0.11844359]
 [ 0.82819937  0.5223803 ]
 [ 0.11563321  0.6246321 ]
 [ 0.42203283  0.88197267]]
[[ 0.         -0.29469367 -0.13367889 -0.38210652 -0.01710326 -0.36750294
  -0.32438354  0.09535371 -0.61721245 -0.31081284]]
[[-0.69833053 -0.60388367 -0.61525047 -0.49644049 -0.37646551 -0.10460424
  -0.61440207 -0.21046536 -0.10821356  0.14912701]]
[[ 0.29469367  0.          0.16101478 -0.08741285  0.27759041 -0.07280927
  -0.02968987  0.39004738 -0.32251878 -0.01611917]]
[[-0.40363686 -0.30919    -0.3205568  -0.20174682 -0.08177184  0.19008943
  -0.3197084   0.08422831  0.18648011  0.44382068]]
[[ 0.13367889 -0.16101478  0.         -0.24842763  0.11657563 -0.23382405
  -0.19070465  0.2290326  -0.48353356 -0.17713395]]
[[-0.56465164 -0.47020478 -0.48157158 -0.3627616  -0.24278662  0.02907464
  -0.48072318 -0.07678647

Случайно расположить p элементов в 2D массив

In [126]:
a = np.arange(8)
np.random.shuffle(a)
a = a.reshape((2, 4))
a

array([[2, 0, 5, 6],
       [7, 3, 4, 1]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [144]:
a = np.array([1, 2, 3, 4, 5])
b = np.zeros(len(a) + (len(a) - 1) * 3)
b[::3+1] = a
b

array([ 1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  4.,
        0.,  0.,  0.,  5.])

Найти наиболее частое значение в массиве

In [146]:
a = np.array([1, 2, 3, 1, 2, 1, 1, 1, 3, 2, 2, 1])
counts = np.bincount(a)
np.argmax(counts)

1

Найти n наибольших значений в массиве

In [159]:
n = 5
a = np.array([10, 21, 13, 1, 2, 5, 7, 81, 31, 12, 21])
a = np.sort(a)
print(a)
a[-n:]

[ 1  2  5  7 10 12 13 21 21 31 81]


array([13, 21, 21, 31, 81])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [12]:
import pandas as pd
df = pd.DataFrame.from_csv('en.openfoodfacts.org.products.tsv', sep='\t')

/Users/andrewlarin/anaconda2/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2821: DtypeWarning: Columns (3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):


Посмотреть первые 5 записей

In [13]:
df.head(5)

url  \
code                                                               
0000000003087  http://world-en.openfoodfacts.org/product/0000...   
0000000004530  http://world-en.openfoodfacts.org/product/0000...   
0000000004559  http://world-en.openfoodfacts.org/product/0000...   
0000000016087  http://world-en.openfoodfacts.org/product/0000...   
0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                                  creator   created_t      created_datetime  \
code                                                                          
0000000003087  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
0000000004530             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
0000000004559             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
0000000016087             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
0000000016094             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

              last_modified_t last_modified_datetime  \
code                                                   
0000000003087      1474103893   2016-09-17T09:18:13Z   
0000000004530      1489069957   2017-03-09T14:32:37Z   
0000000004559      1489069957   2017-03-09T14:32:37Z   
0000000016087      1489055731   2017-03-09T10:35:31Z   
0000000016094      1489055653   2017-03-09T10:34:13Z   

                                 product_name generic_name quantity packaging  \
code                                                                            
0000000003087              Farine de blé noir          NaN      1kg       NaN   
0000000004530  Banana Chips Sweetened (Whole)          NaN      NaN       NaN   
0000000004559                         Peanuts          NaN      NaN       NaN   
0000000016087          Organic Salted Nut Mix          NaN      NaN       NaN   
0000000016094                 Organic Polenta          NaN      NaN       NaN   

                      ...         fruits-vegetables-nuts_100g  \
code                  ...                                       
0000000003087         ...                                 NaN   
0000000004530         ...                                 NaN   
0000000004559         ...                                 NaN   
0000000016087         ...                                 NaN   
0000000016094         ...                                 NaN   

              fruits-vegetables-nuts-estimate_100g  \
code                                                 
0000000003087                                  NaN   
0000000004530                                  NaN   
0000000004559                                  NaN   
0000000016087                                  NaN   
0000000016094                                  NaN   

              collagen-meat-protein-ratio_100g cocoa_100g chlorophyl_100g  \
code                                                                        
0000000003087                              NaN        NaN             NaN   
0000000004530                              NaN        NaN             NaN   
0000000004559                              NaN        NaN             NaN   
0000000016087                              NaN        NaN             NaN   
0000000016094                              NaN        NaN             NaN   

              carbon-footprint_100g nutrition-score-fr_100g  \
code                                                          
0000000003087                   NaN                     NaN   
0000000004530                   NaN                    14.0   
0000000004559                   NaN                     0.0   
0000000016087                   NaN                    12.0   
0000000016094                   NaN                     NaN   

              nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
code                                                                           
0000000003087                     NaN                 NaN                 NaN  
000000000453

Сколько наблюдений в наборе данных?


In [34]:
df.shape[0]

356027

Сколько столбцов в наборе данных?

In [21]:
len(df.columns)

162

Напечатайте все названия столбцов

In [22]:
for c in df.columns:
    print(c)

url
creator
created_t
created_datetime
last_modified_t
last_modified_datetime
product_name
generic_name
quantity
packaging
packaging_tags
brands
brands_tags
categories
categories_tags
categories_en
origins
origins_tags
manufacturing_places
manufacturing_places_tags
labels
labels_tags
labels_en
emb_codes
emb_codes_tags
first_packaging_code_geo
cities
cities_tags
purchase_places
stores
countries
countries_tags
countries_en
ingredients_text
allergens
allergens_en
traces
traces_tags
traces_en
serving_size
no_nutriments
additives_n
additives
additives_tags
additives_en
ingredients_from_palm_oil_n
ingredients_from_palm_oil
ingredients_from_palm_oil_tags
ingredients_that_may_be_from_palm_oil_n
ingredients_that_may_be_from_palm_oil
ingredients_that_may_be_from_palm_oil_tags
nutrition_grade_uk
nutrition_grade_fr
pnns_groups_1
pnns_groups_2
states
states_tags
states_en
main_category
main_category_en
image_url
image_small_url
energy_100g
energy-from-fat_100g
fat_100g
saturated-fat_100g
-butyric-a

Какое название у 105 столбца?

In [25]:
df.columns[105]

'-lactose_100g'

Какой тип наблюдений в 105 столбце?

In [28]:
df.dtypes[df.columns[105]]

dtype('float64')

Как проиндексирован набор данных?

In [38]:
for i in df.index.values[:10]:
    print(i)

0000000003087
0000000004530
0000000004559
0000000016087
0000000016094
0000000016100
0000000016117
0000000016124
0000000016193
0000000016513


Каково значение имени продукта в 19-м наблюдении?

In [43]:
df.loc[df.index.values[19]].product_name

'Organic Oat Groats'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

Как много продуктов стоят более чем $10.00?

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

Отсортировать по имени предмета

Сколько было заказано самого дорогого предмета?

Сколько раз был заказан предмет "Veggie Salad Bowl"?

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?